f = open('hello.txt', 'w')
f.write('Безмозглый широковещательный цифровой передатчик сужающихся экспонент.')
f.close()
f = open('hello.txt', 'a')
f.write('Однажды съев фейхоа, я, как зацикленный, ностальгирую всё чаще и больше по этому чуду.')
f.close()
f = open('hello.txt', 'r')
print(f.read())
f.close()
