test = open("Политех.desktop","w")
test.write("[Desktop Entry]\n")
test.write("Name=Политехнический институт\n")
test.write("GenericName=POLYTECH\n")
test.write("Comment=Переход на сайт политеха\n")
test.write("URL=https://politeh.pnzgu.ru/\n")
test.write("Type=Link\n")
test.write("Icon=text-html\n")
test.write("Terminal=false\n")
test.close()
